version: "3.4"

services:
  misakapics:
    # Alternatively, you may use "yyoung01/nazurin:latest"
    image: nazurin
    container_name: misakapics
    build: .
    env_file:
      - ".env.misakapics"
    volumes:
      - "./datas:/app/data"
    ports:
      - "127.0.0.1:10002:80"
    restart: unless-stopped

  misakah:
    image: nazurin
    container_name: misakah
    build: .
    env_file:
      - ".env.misakah"
    volumes:
      - "./datah:/app/data"
    ports:
      - "127.0.0.1:10003:80"
    restart: unless-stopped
